# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/banking_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Email Settings (Verify these with your EmailUtil.java)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=navyan1809@gmail.com
spring.mail.password=thww gqfm fnpy bpou
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true